name: Continuous Integration
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  format_checking:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
      - name: Format Checking
        run: |
          StyLua src --check